# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kaoru/Documents/GitHub/ZaqroU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kaoru/Documents/GitHub/ZaqroU

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaoru/Documents/GitHub/ZaqroU/CMakeFiles /home/kaoru/Documents/GitHub/ZaqroU//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaoru/Documents/GitHub/ZaqroU/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/kaoru/Documents/GitHub/ZaqroU/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Zaqro_U

# Build rule for target.
Zaqro_U: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Zaqro_U
.PHONY : Zaqro_U

# fast build rule for target.
Zaqro_U/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/build
.PHONY : Zaqro_U/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/raim/Raim.o: src/raim/Raim.cpp.o
.PHONY : src/raim/Raim.o

# target to build an object file
src/raim/Raim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/Raim.cpp.o
.PHONY : src/raim/Raim.cpp.o

src/raim/Raim.i: src/raim/Raim.cpp.i
.PHONY : src/raim/Raim.i

# target to preprocess a source file
src/raim/Raim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/Raim.cpp.i
.PHONY : src/raim/Raim.cpp.i

src/raim/Raim.s: src/raim/Raim.cpp.s
.PHONY : src/raim/Raim.s

# target to generate assembly for a file
src/raim/Raim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/Raim.cpp.s
.PHONY : src/raim/Raim.cpp.s

src/raim/ui/NotificationManager.o: src/raim/ui/NotificationManager.cpp.o
.PHONY : src/raim/ui/NotificationManager.o

# target to build an object file
src/raim/ui/NotificationManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/NotificationManager.cpp.o
.PHONY : src/raim/ui/NotificationManager.cpp.o

src/raim/ui/NotificationManager.i: src/raim/ui/NotificationManager.cpp.i
.PHONY : src/raim/ui/NotificationManager.i

# target to preprocess a source file
src/raim/ui/NotificationManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/NotificationManager.cpp.i
.PHONY : src/raim/ui/NotificationManager.cpp.i

src/raim/ui/NotificationManager.s: src/raim/ui/NotificationManager.cpp.s
.PHONY : src/raim/ui/NotificationManager.s

# target to generate assembly for a file
src/raim/ui/NotificationManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/NotificationManager.cpp.s
.PHONY : src/raim/ui/NotificationManager.cpp.s

src/raim/ui/RaimUI.o: src/raim/ui/RaimUI.cpp.o
.PHONY : src/raim/ui/RaimUI.o

# target to build an object file
src/raim/ui/RaimUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/RaimUI.cpp.o
.PHONY : src/raim/ui/RaimUI.cpp.o

src/raim/ui/RaimUI.i: src/raim/ui/RaimUI.cpp.i
.PHONY : src/raim/ui/RaimUI.i

# target to preprocess a source file
src/raim/ui/RaimUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/RaimUI.cpp.i
.PHONY : src/raim/ui/RaimUI.cpp.i

src/raim/ui/RaimUI.s: src/raim/ui/RaimUI.cpp.s
.PHONY : src/raim/ui/RaimUI.s

# target to generate assembly for a file
src/raim/ui/RaimUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/RaimUI.cpp.s
.PHONY : src/raim/ui/RaimUI.cpp.s

src/raim/ui/style/IRaimUI_Theme.o: src/raim/ui/style/IRaimUI_Theme.cpp.o
.PHONY : src/raim/ui/style/IRaimUI_Theme.o

# target to build an object file
src/raim/ui/style/IRaimUI_Theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/style/IRaimUI_Theme.cpp.o
.PHONY : src/raim/ui/style/IRaimUI_Theme.cpp.o

src/raim/ui/style/IRaimUI_Theme.i: src/raim/ui/style/IRaimUI_Theme.cpp.i
.PHONY : src/raim/ui/style/IRaimUI_Theme.i

# target to preprocess a source file
src/raim/ui/style/IRaimUI_Theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/style/IRaimUI_Theme.cpp.i
.PHONY : src/raim/ui/style/IRaimUI_Theme.cpp.i

src/raim/ui/style/IRaimUI_Theme.s: src/raim/ui/style/IRaimUI_Theme.cpp.s
.PHONY : src/raim/ui/style/IRaimUI_Theme.s

# target to generate assembly for a file
src/raim/ui/style/IRaimUI_Theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/style/IRaimUI_Theme.cpp.s
.PHONY : src/raim/ui/style/IRaimUI_Theme.cpp.s

src/raim/ui/tab/IRaimTab.o: src/raim/ui/tab/IRaimTab.cpp.o
.PHONY : src/raim/ui/tab/IRaimTab.o

# target to build an object file
src/raim/ui/tab/IRaimTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/IRaimTab.cpp.o
.PHONY : src/raim/ui/tab/IRaimTab.cpp.o

src/raim/ui/tab/IRaimTab.i: src/raim/ui/tab/IRaimTab.cpp.i
.PHONY : src/raim/ui/tab/IRaimTab.i

# target to preprocess a source file
src/raim/ui/tab/IRaimTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/IRaimTab.cpp.i
.PHONY : src/raim/ui/tab/IRaimTab.cpp.i

src/raim/ui/tab/IRaimTab.s: src/raim/ui/tab/IRaimTab.cpp.s
.PHONY : src/raim/ui/tab/IRaimTab.s

# target to generate assembly for a file
src/raim/ui/tab/IRaimTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/IRaimTab.cpp.s
.PHONY : src/raim/ui/tab/IRaimTab.cpp.s

src/raim/ui/tab/RaimTabManager.o: src/raim/ui/tab/RaimTabManager.cpp.o
.PHONY : src/raim/ui/tab/RaimTabManager.o

# target to build an object file
src/raim/ui/tab/RaimTabManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/RaimTabManager.cpp.o
.PHONY : src/raim/ui/tab/RaimTabManager.cpp.o

src/raim/ui/tab/RaimTabManager.i: src/raim/ui/tab/RaimTabManager.cpp.i
.PHONY : src/raim/ui/tab/RaimTabManager.i

# target to preprocess a source file
src/raim/ui/tab/RaimTabManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/RaimTabManager.cpp.i
.PHONY : src/raim/ui/tab/RaimTabManager.cpp.i

src/raim/ui/tab/RaimTabManager.s: src/raim/ui/tab/RaimTabManager.cpp.s
.PHONY : src/raim/ui/tab/RaimTabManager.s

# target to generate assembly for a file
src/raim/ui/tab/RaimTabManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/RaimTabManager.cpp.s
.PHONY : src/raim/ui/tab/RaimTabManager.cpp.s

src/raim/ui/tab/impl/DebugTab.o: src/raim/ui/tab/impl/DebugTab.cpp.o
.PHONY : src/raim/ui/tab/impl/DebugTab.o

# target to build an object file
src/raim/ui/tab/impl/DebugTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/DebugTab.cpp.o
.PHONY : src/raim/ui/tab/impl/DebugTab.cpp.o

src/raim/ui/tab/impl/DebugTab.i: src/raim/ui/tab/impl/DebugTab.cpp.i
.PHONY : src/raim/ui/tab/impl/DebugTab.i

# target to preprocess a source file
src/raim/ui/tab/impl/DebugTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/DebugTab.cpp.i
.PHONY : src/raim/ui/tab/impl/DebugTab.cpp.i

src/raim/ui/tab/impl/DebugTab.s: src/raim/ui/tab/impl/DebugTab.cpp.s
.PHONY : src/raim/ui/tab/impl/DebugTab.s

# target to generate assembly for a file
src/raim/ui/tab/impl/DebugTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/DebugTab.cpp.s
.PHONY : src/raim/ui/tab/impl/DebugTab.cpp.s

src/raim/ui/tab/impl/MemoryEditorTab.o: src/raim/ui/tab/impl/MemoryEditorTab.cpp.o
.PHONY : src/raim/ui/tab/impl/MemoryEditorTab.o

# target to build an object file
src/raim/ui/tab/impl/MemoryEditorTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/MemoryEditorTab.cpp.o
.PHONY : src/raim/ui/tab/impl/MemoryEditorTab.cpp.o

src/raim/ui/tab/impl/MemoryEditorTab.i: src/raim/ui/tab/impl/MemoryEditorTab.cpp.i
.PHONY : src/raim/ui/tab/impl/MemoryEditorTab.i

# target to preprocess a source file
src/raim/ui/tab/impl/MemoryEditorTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/MemoryEditorTab.cpp.i
.PHONY : src/raim/ui/tab/impl/MemoryEditorTab.cpp.i

src/raim/ui/tab/impl/MemoryEditorTab.s: src/raim/ui/tab/impl/MemoryEditorTab.cpp.s
.PHONY : src/raim/ui/tab/impl/MemoryEditorTab.s

# target to generate assembly for a file
src/raim/ui/tab/impl/MemoryEditorTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/MemoryEditorTab.cpp.s
.PHONY : src/raim/ui/tab/impl/MemoryEditorTab.cpp.s

src/raim/ui/tab/impl/codes/CodesTab.o: src/raim/ui/tab/impl/codes/CodesTab.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab.o

# target to build an object file
src/raim/ui/tab/impl/codes/CodesTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab.cpp.o

src/raim/ui/tab/impl/codes/CodesTab.i: src/raim/ui/tab/impl/codes/CodesTab.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab.i

# target to preprocess a source file
src/raim/ui/tab/impl/codes/CodesTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab.cpp.i

src/raim/ui/tab/impl/codes/CodesTab.s: src/raim/ui/tab/impl/codes/CodesTab.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab.s

# target to generate assembly for a file
src/raim/ui/tab/impl/codes/CodesTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab.cpp.s

src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.o: src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.o

# target to build an object file
src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.o

src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.i: src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.i

# target to preprocess a source file
src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.i

src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.s: src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.s

# target to generate assembly for a file
src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.cpp.s

src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.o: src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.o

# target to build an object file
src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.o

src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.i: src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.i

# target to preprocess a source file
src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.i

src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.s: src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.s

# target to generate assembly for a file
src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.cpp.s

src/raim/ui/tab/impl/codes/CodesTab_UI.o: src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_UI.o

# target to build an object file
src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.o
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.o

src/raim/ui/tab/impl/codes/CodesTab_UI.i: src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_UI.i

# target to preprocess a source file
src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.i
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.i

src/raim/ui/tab/impl/codes/CodesTab_UI.s: src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_UI.s

# target to generate assembly for a file
src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.s
.PHONY : src/raim/ui/tab/impl/codes/CodesTab_UI.cpp.s

src/raim/ui/tab/impl/settings/SettingsTab.o: src/raim/ui/tab/impl/settings/SettingsTab.cpp.o
.PHONY : src/raim/ui/tab/impl/settings/SettingsTab.o

# target to build an object file
src/raim/ui/tab/impl/settings/SettingsTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/settings/SettingsTab.cpp.o
.PHONY : src/raim/ui/tab/impl/settings/SettingsTab.cpp.o

src/raim/ui/tab/impl/settings/SettingsTab.i: src/raim/ui/tab/impl/settings/SettingsTab.cpp.i
.PHONY : src/raim/ui/tab/impl/settings/SettingsTab.i

# target to preprocess a source file
src/raim/ui/tab/impl/settings/SettingsTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/settings/SettingsTab.cpp.i
.PHONY : src/raim/ui/tab/impl/settings/SettingsTab.cpp.i

src/raim/ui/tab/impl/settings/SettingsTab.s: src/raim/ui/tab/impl/settings/SettingsTab.cpp.s
.PHONY : src/raim/ui/tab/impl/settings/SettingsTab.s

# target to generate assembly for a file
src/raim/ui/tab/impl/settings/SettingsTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/raim/ui/tab/impl/settings/SettingsTab.cpp.s
.PHONY : src/raim/ui/tab/impl/settings/SettingsTab.cpp.s

src/utils/Config.o: src/utils/Config.cpp.o
.PHONY : src/utils/Config.o

# target to build an object file
src/utils/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/Config.cpp.o
.PHONY : src/utils/Config.cpp.o

src/utils/Config.i: src/utils/Config.cpp.i
.PHONY : src/utils/Config.i

# target to preprocess a source file
src/utils/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/Config.cpp.i
.PHONY : src/utils/Config.cpp.i

src/utils/Config.s: src/utils/Config.cpp.s
.PHONY : src/utils/Config.s

# target to generate assembly for a file
src/utils/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/Config.cpp.s
.PHONY : src/utils/Config.cpp.s

src/utils/TCPGecko.o: src/utils/TCPGecko.cpp.o
.PHONY : src/utils/TCPGecko.o

# target to build an object file
src/utils/TCPGecko.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/TCPGecko.cpp.o
.PHONY : src/utils/TCPGecko.cpp.o

src/utils/TCPGecko.i: src/utils/TCPGecko.cpp.i
.PHONY : src/utils/TCPGecko.i

# target to preprocess a source file
src/utils/TCPGecko.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/TCPGecko.cpp.i
.PHONY : src/utils/TCPGecko.cpp.i

src/utils/TCPGecko.s: src/utils/TCPGecko.cpp.s
.PHONY : src/utils/TCPGecko.s

# target to generate assembly for a file
src/utils/TCPGecko.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/TCPGecko.cpp.s
.PHONY : src/utils/TCPGecko.cpp.s

src/utils/TitleIdParser.o: src/utils/TitleIdParser.cpp.o
.PHONY : src/utils/TitleIdParser.o

# target to build an object file
src/utils/TitleIdParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/TitleIdParser.cpp.o
.PHONY : src/utils/TitleIdParser.cpp.o

src/utils/TitleIdParser.i: src/utils/TitleIdParser.cpp.i
.PHONY : src/utils/TitleIdParser.i

# target to preprocess a source file
src/utils/TitleIdParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/TitleIdParser.cpp.i
.PHONY : src/utils/TitleIdParser.cpp.i

src/utils/TitleIdParser.s: src/utils/TitleIdParser.cpp.s
.PHONY : src/utils/TitleIdParser.s

# target to generate assembly for a file
src/utils/TitleIdParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/TitleIdParser.cpp.s
.PHONY : src/utils/TitleIdParser.cpp.s

src/utils/downloader.o: src/utils/downloader.cpp.o
.PHONY : src/utils/downloader.o

# target to build an object file
src/utils/downloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/downloader.cpp.o
.PHONY : src/utils/downloader.cpp.o

src/utils/downloader.i: src/utils/downloader.cpp.i
.PHONY : src/utils/downloader.i

# target to preprocess a source file
src/utils/downloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/downloader.cpp.i
.PHONY : src/utils/downloader.cpp.i

src/utils/downloader.s: src/utils/downloader.cpp.s
.PHONY : src/utils/downloader.s

# target to generate assembly for a file
src/utils/downloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/downloader.cpp.s
.PHONY : src/utils/downloader.cpp.s

src/utils/imgui_utils.o: src/utils/imgui_utils.cpp.o
.PHONY : src/utils/imgui_utils.o

# target to build an object file
src/utils/imgui_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/imgui_utils.cpp.o
.PHONY : src/utils/imgui_utils.cpp.o

src/utils/imgui_utils.i: src/utils/imgui_utils.cpp.i
.PHONY : src/utils/imgui_utils.i

# target to preprocess a source file
src/utils/imgui_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/imgui_utils.cpp.i
.PHONY : src/utils/imgui_utils.cpp.i

src/utils/imgui_utils.s: src/utils/imgui_utils.cpp.s
.PHONY : src/utils/imgui_utils.s

# target to generate assembly for a file
src/utils/imgui_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Zaqro_U.dir/build.make CMakeFiles/Zaqro_U.dir/src/utils/imgui_utils.cpp.s
.PHONY : src/utils/imgui_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Zaqro_U"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/raim/Raim.o"
	@echo "... src/raim/Raim.i"
	@echo "... src/raim/Raim.s"
	@echo "... src/raim/ui/NotificationManager.o"
	@echo "... src/raim/ui/NotificationManager.i"
	@echo "... src/raim/ui/NotificationManager.s"
	@echo "... src/raim/ui/RaimUI.o"
	@echo "... src/raim/ui/RaimUI.i"
	@echo "... src/raim/ui/RaimUI.s"
	@echo "... src/raim/ui/style/IRaimUI_Theme.o"
	@echo "... src/raim/ui/style/IRaimUI_Theme.i"
	@echo "... src/raim/ui/style/IRaimUI_Theme.s"
	@echo "... src/raim/ui/tab/IRaimTab.o"
	@echo "... src/raim/ui/tab/IRaimTab.i"
	@echo "... src/raim/ui/tab/IRaimTab.s"
	@echo "... src/raim/ui/tab/RaimTabManager.o"
	@echo "... src/raim/ui/tab/RaimTabManager.i"
	@echo "... src/raim/ui/tab/RaimTabManager.s"
	@echo "... src/raim/ui/tab/impl/DebugTab.o"
	@echo "... src/raim/ui/tab/impl/DebugTab.i"
	@echo "... src/raim/ui/tab/impl/DebugTab.s"
	@echo "... src/raim/ui/tab/impl/MemoryEditorTab.o"
	@echo "... src/raim/ui/tab/impl/MemoryEditorTab.i"
	@echo "... src/raim/ui/tab/impl/MemoryEditorTab.s"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab.o"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab.i"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab.s"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.o"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.i"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_CodeFrameUI.s"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.o"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.i"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_CodesFrameUI.s"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_UI.o"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_UI.i"
	@echo "... src/raim/ui/tab/impl/codes/CodesTab_UI.s"
	@echo "... src/raim/ui/tab/impl/settings/SettingsTab.o"
	@echo "... src/raim/ui/tab/impl/settings/SettingsTab.i"
	@echo "... src/raim/ui/tab/impl/settings/SettingsTab.s"
	@echo "... src/utils/Config.o"
	@echo "... src/utils/Config.i"
	@echo "... src/utils/Config.s"
	@echo "... src/utils/TCPGecko.o"
	@echo "... src/utils/TCPGecko.i"
	@echo "... src/utils/TCPGecko.s"
	@echo "... src/utils/TitleIdParser.o"
	@echo "... src/utils/TitleIdParser.i"
	@echo "... src/utils/TitleIdParser.s"
	@echo "... src/utils/downloader.o"
	@echo "... src/utils/downloader.i"
	@echo "... src/utils/downloader.s"
	@echo "... src/utils/imgui_utils.o"
	@echo "... src/utils/imgui_utils.i"
	@echo "... src/utils/imgui_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/kaoru/Documents/GitHub/ZaqroU/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

